/**
 * AUTO-GENERATED by `npm run gen:api` (openapi-zod-client, from the backend's OpenAPI spec).
 * Do not edit by hand -- changes will be overwritten. Run `npm run gen:api` while the backend
 * is running to refresh after changing `backend/TodoApi/Dtos/*.cs`.
 *
 * We could have written these types by hand instead of generating them which I would say is fine for
 * a single-person application, but the task instructions call out "communication between frontend and backend"
 * as an evaluation criterion, so I added this codegen which enables compile-time and runtime validation.
 * The cost is additional complexity (having to understand zod) and there is some added additional latency
 * (though negligible) to do the runtime validation.
 *
 * Note that `npm run gen:api` has to be enforced in CI/CD pipelines for this to be safe which I do not do.
 */

import { z } from "zod";

const ProjectResponse = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string().nullish(),
  isDefault: z.boolean(),
});
const CreateProjectRequest = z
  .object({ name: z.string().nullable(), description: z.string().nullable() })
  .partial();
const UpdateProjectRequest = z
  .object({ name: z.string().nullable(), description: z.string().nullable() })
  .partial();
const TaskResponse = z.object({
  id: z.number().int(),
  title: z.string(),
  description: z.string().nullish(),
  projectId: z.number().int(),
  order: z.number().int(),
  isComplete: z.boolean(),
  completedAt: z.string().datetime({ offset: true }).nullish(),
  createdAt: z.string().datetime({ offset: true }),
});
const CreateTaskRequest = z
  .object({ title: z.string().nullable(), description: z.string().nullable() })
  .partial();
const ReorderTasksRequest = z.object({
  orderedTaskIds: z.array(z.number().int()),
});
const UpdateTaskRequest = z
  .object({ title: z.string().nullable(), description: z.string().nullable() })
  .partial();
const MoveTaskRequest = z.object({ targetProjectId: z.number().int() });

export const schemas = {
  ProjectResponse,
  CreateProjectRequest,
  UpdateProjectRequest,
  TaskResponse,
  CreateTaskRequest,
  ReorderTasksRequest,
  UpdateTaskRequest,
  MoveTaskRequest,
};

export type ProjectResponse = z.infer<typeof ProjectResponse>;
export type CreateProjectRequest = z.infer<typeof CreateProjectRequest>;
export type UpdateProjectRequest = z.infer<typeof UpdateProjectRequest>;
export type TaskResponse = z.infer<typeof TaskResponse>;
export type CreateTaskRequest = z.infer<typeof CreateTaskRequest>;
export type ReorderTasksRequest = z.infer<typeof ReorderTasksRequest>;
export type UpdateTaskRequest = z.infer<typeof UpdateTaskRequest>;
export type MoveTaskRequest = z.infer<typeof MoveTaskRequest>;
