/**
 * AUTO-GENERATED by `npm run gen:api` (openapi-zod-client, from the backend's OpenAPI spec).
 * Do not edit by hand -- changes will be overwritten. Run `npm run gen:api` while the backend
 * is running to refresh after changing `backend/TodoApi/Dtos/*.cs`.
 *
 * We could have written these types by hand instead of generating them which I would say is fine for
 * an application with a single developer, but the task instructions call out "communication between frontend and backend"
 * as an evaluation criterion, so I added this codegen which enables compile-time and runtime validation.
 * The cost is additional complexity (having to understand zod and hbs syntax) and there is some added additional latency
 * (though negligible) to do the runtime validation.
 *
 * Note that `npm run gen:api` has to be enforced in CI/CD pipelines for this to be safe which I did not do.
 * which is additional complexity.
 */

import { z } from "zod";

const ProjectResponse = z.object({
  id: z.number().int(),
  name: z.string(),
  order: z.number().int(),
  createdAt: z.string().datetime({ offset: true }),
});
const CreateProjectRequest = z.object({ name: z.string().min(1).max(200) });
const ReorderProjectsRequest = z.object({
  orderedProjectIds: z.array(z.number().int()),
});
const UpdateProjectRequest = z.object({ name: z.string().min(1).max(200) });
const TaskResponse = z.object({
  id: z.number().int(),
  title: z.string(),
  description: z.string().nullish(),
  projectId: z.number().int(),
  order: z.number().int(),
  isComplete: z.boolean(),
  completedAt: z.string().datetime({ offset: true }).nullish(),
  createdAt: z.string().datetime({ offset: true }),
});
const CreateTaskRequest = z.object({
  projectId: z.number().int(),
  title: z.string().min(1).max(200),
  description: z.string().max(2000).nullish(),
});
const PatchTaskRequest = z
  .object({
    title: z.string().min(1).max(200).nullable(),
    description: z.string().max(2000).nullable(),
    isComplete: z.boolean().nullable(),
    projectId: z.number().int().nullable(),
  })
  .partial();
const ReorderTasksRequest = z.object({
  projectId: z.number().int(),
  orderedTaskIds: z.array(z.number().int()),
});

export const schemas = {
  ProjectResponse,
  CreateProjectRequest,
  ReorderProjectsRequest,
  UpdateProjectRequest,
  TaskResponse,
  CreateTaskRequest,
  PatchTaskRequest,
  ReorderTasksRequest,
};

export type ProjectResponse = z.infer<typeof ProjectResponse>;
export type CreateProjectRequest = z.infer<typeof CreateProjectRequest>;
export type ReorderProjectsRequest = z.infer<typeof ReorderProjectsRequest>;
export type UpdateProjectRequest = z.infer<typeof UpdateProjectRequest>;
export type TaskResponse = z.infer<typeof TaskResponse>;
export type CreateTaskRequest = z.infer<typeof CreateTaskRequest>;
export type PatchTaskRequest = z.infer<typeof PatchTaskRequest>;
export type ReorderTasksRequest = z.infer<typeof ReorderTasksRequest>;
