/**
 * DTO types generated from the backend's OpenAPI spec (see `schema.ts`, generated by
 * `openapi-typescript` from Swashbuckle's output -- run `npm run gen:api` while the backend is
 * running to refresh after changing `backend/TodoApi/Dtos/*.cs`). Regenerating from a live spec
 * beats hand-mirroring the C# types: it can't drift, and it catches shape changes at compile
 * time instead of at runtime.
 */

import type { components } from './schema';

// ---- Projects ----

export type ProjectResponse = components['schemas']['ProjectResponse'];
export type CreateProjectRequest = components['schemas']['CreateProjectRequest'];
export type UpdateProjectRequest = components['schemas']['UpdateProjectRequest'];

// ---- Tasks ----

export type TaskResponse = components['schemas']['TaskResponse'];
export type CreateTaskRequest = components['schemas']['CreateTaskRequest'];
export type UpdateTaskRequest = components['schemas']['UpdateTaskRequest'];
export type MoveTaskRequest = components['schemas']['MoveTaskRequest'];
export type ReorderTasksRequest = components['schemas']['ReorderTasksRequest'];

// ---- Errors (RFC 7807 ProblemDetails, see ExceptionHandlingMiddleware.cs) ----

export interface ProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  /** Present on 400 validation errors (ValidationProblemDetails); maps field name -> messages. */
  errors?: { [field: string]: string[] };
}
