/**
 * DTO types generated from the backend's OpenAPI spec (see `schema.ts`, generated by
 * `openapi-typescript` from Swashbuckle's output -- run `npm run gen:api` while the backend is
 * running to refresh after changing `backend/TodoApi/Dtos/*.cs`).
 */

import type { components } from './schema';

// ---- Projects ----

export type ProjectResponse = components['schemas']['ProjectResponse'];
export type CreateProjectRequest = components['schemas']['CreateProjectRequest'];
export type UpdateProjectRequest = components['schemas']['UpdateProjectRequest'];

// ---- Tasks ----

export type TaskResponse = components['schemas']['TaskResponse'];
export type CreateTaskRequest = components['schemas']['CreateTaskRequest'];
export type UpdateTaskRequest = components['schemas']['UpdateTaskRequest'];
export type MoveTaskRequest = components['schemas']['MoveTaskRequest'];
export type ReorderTasksRequest = components['schemas']['ReorderTasksRequest'];

// ---- Errors (RFC 7807 ProblemDetails, see ExceptionHandlingMiddleware.cs) ----
//
// Hand-written, not generated: error bodies are written directly to the response stream by
// ExceptionHandlingMiddleware after an exception is thrown, not returned from an endpoint's
// declared return type. Swashbuckle builds the OpenAPI spec by inspecting endpoint return
// types/ProducesResponseType attributes, so it never sees this path and omits ProblemDetails
// from schema.ts entirely. Fixable by adding `.Produces<ProblemDetails>(status)` to every
// endpoint chain for every status code it can throw, but that's per-endpoint boilerplate for
// one shared shape -- not worth it here.

export interface ProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  /** Present on 400 validation errors (ValidationProblemDetails); maps field name -> messages. */
  errors?: { [field: string]: string[] };
}
